# Generated by Django 5.0.6 on 2024-06-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLogins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('id_type', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('success', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_logins',
            },
        ),
        migrations.CreateModel(
            name='AuthTokenLogins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('id_type', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('success', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_token_logins',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('displayname', models.CharField(max_length=250)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.IntegerField()),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AuthRememberTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=255, unique=True)),
                ('hashedvalidator', models.CharField(db_column='hashedValidator', max_length=255)),
                ('expires', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rgadmin.users')),
            ],
            options={
                'db_table': 'auth_remember_tokens',
            },
        ),
        migrations.CreateModel(
            name='AuthPermissionsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rgadmin.users')),
            ],
            options={
                'db_table': 'auth_permissions_users',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rgadmin.users')),
            ],
            options={
                'db_table': 'auth_groups_users',
            },
        ),
        migrations.CreateModel(
            name='AuthIdentities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('secret', models.CharField(max_length=255)),
                ('secret2', models.CharField(blank=True, max_length=255, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('force_reset', models.IntegerField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rgadmin.users')),
            ],
            options={
                'db_table': 'auth_identities',
                'unique_together': {('type', 'secret')},
            },
        ),
    ]
