# Generated by Django 4.1.13 on 2024-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapweb', '0003_remove_siteurls_question_siteurls_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteurls',
            name='site_page',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
