# Generated by Django 4.1.13 on 2024-09-26 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapweb', '0004_siteurls_site_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site_page_id', models.CharField(max_length=1200, null=True)),
                ('content', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('site_id', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.DO_NOTHING, to='scrapweb.site')),
            ],
        ),
    ]
