# Generated by Django 4.1.13 on 2024-09-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapweb', '0005_sitecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='site_id',
            field=models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.DO_NOTHING, to='scrapweb.site'),
        ),
        migrations.AlterField(
            model_name='siteurls',
            name='site_id',
            field=models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.DO_NOTHING, to='scrapweb.site'),
        ),
    ]
