# Generated by Django 5.0.6 on 2024-08-16 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('prompt', models.CharField(max_length=10000, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentQuestions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('agent_id', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentAnswers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('agent_id', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agentquestions')),
            ],
        ),
        migrations.CreateModel(
            name='AgentResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ai_response', models.CharField(max_length=10000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('agent_id', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
