# Generated by Django 5.0.6 on 2024-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentanswers',
            name='ans_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='ans_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
